
public class Calulate extends javax.swing.JFrame {

    public Calulate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        congBtn = new javax.swing.JButton();
        truBtn = new javax.swing.JButton();
        nhanBtn = new javax.swing.JButton();
        chiaBtn = new javax.swing.JButton();
        ACbtn = new javax.swing.JButton();
        txtShow = new javax.swing.JTextField();
        kqTxt = new javax.swing.JLabel();
        num1Txt = new javax.swing.JTextField();
        num2Txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setForeground(new java.awt.Color(255, 204, 0));

        congBtn.setText("+");
        congBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                congBtnActionPerformed(evt);
            }
        });

        truBtn.setText("-");
        truBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truBtnActionPerformed(evt);
            }
        });

        nhanBtn.setText("X");
        nhanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanBtnActionPerformed(evt);
            }
        });

        chiaBtn.setText("/");
        chiaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiaBtnActionPerformed(evt);
            }
        });

        ACbtn.setText("AC");
        ACbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACbtnActionPerformed(evt);
            }
        });

        txtShow.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtShow.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtShow.setEnabled(false);

        kqTxt.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        kqTxt.setText("MÁY TÍNH LỎ");

        num1Txt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num1Txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        num1Txt.setToolTipText("");

        num2Txt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num2Txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(kqTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtShow, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(num1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(chiaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nhanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(truBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                    .addComponent(congBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(num2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(ACbtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(kqTxt)
                .addGap(18, 18, 18)
                .addComponent(txtShow, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chiaBtn)
                            .addComponent(truBtn))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nhanBtn)
                            .addComponent(congBtn))))
                .addGap(18, 18, 18)
                .addComponent(ACbtn)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
////// Nút phép tính cộng
    private void congBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_congBtnActionPerformed
        String n1 = num1Txt.getText();
        String n2 = num2Txt.getText();

        try {
            double num1 = Double.parseDouble(n1);
            double num2 = Double.parseDouble(n2);
            double sum = num1 + num2;

            String sumS = String.valueOf(sum);

            txtShow.setText(sumS);
        } catch (NumberFormatException e) {

            txtShow.setText("Vui lòng nhập số hợp lệ");
        }
    }//GEN-LAST:event_congBtnActionPerformed
// Nút phép chia
    private void chiaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiaBtnActionPerformed
      
  String n1 = num1Txt.getText();
        String n2 = num2Txt.getText();

        try {
            double num1 = Double.parseDouble(n1);
            double num2 = Double.parseDouble(n2);

            if (num2 == 0) {
                txtShow.setText("Không thể chia cho 0 ");
            } else {
                double result = num1 / num2;
                txtShow.setText(String.valueOf(result));
            }

        } catch (NumberFormatException ex) {
            txtShow.setText("Vui lòng nhập số hợp lệ ");
        }
    }//GEN-LAST:event_chiaBtnActionPerformed
// Nút phép nhân
    private void nhanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanBtnActionPerformed
        String n1 = num1Txt.getText();
        String n2 = num2Txt.getText();

        try {
            double num1 = Double.parseDouble(n1);
            double num2 = Double.parseDouble(n2);

            double result = num1 * num2;
            txtShow.setText(String.valueOf(result));

        } catch (NumberFormatException ex) {
            txtShow.setText("Vui lòng nhập số hợp lệ.");
        }
    }//GEN-LAST:event_nhanBtnActionPerformed
// AC button
    private void ACbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACbtnActionPerformed
        txtShow.setText("");
    }//GEN-LAST:event_ACbtnActionPerformed
// Nút phép trừ
    private void truBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truBtnActionPerformed
        String n1 = num1Txt.getText();
        String n2 = num2Txt.getText();

        try {
            double num1 = Double.parseDouble(n1);
            double num2 = Double.parseDouble(n2);

            double result = num1 - num2;
            txtShow.setText(String.valueOf(result));

        } catch (NumberFormatException ex) {
            txtShow.setText("Bạn đã nhập sai số, vui lòng nhập lại số.");
        }
    }//GEN-LAST:event_truBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calulate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calulate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calulate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calulate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calulate().setVisible(true);
            }
       
        });
        
    }
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACbtn;
    private javax.swing.JButton chiaBtn;
    private javax.swing.JButton congBtn;
    private javax.swing.JLabel kqTxt;
    private javax.swing.JButton nhanBtn;
    private javax.swing.JTextField num1Txt;
    private javax.swing.JTextField num2Txt;
    private javax.swing.JButton truBtn;
    private javax.swing.JTextField txtShow;
    // End of variables declaration//GEN-END:variables
}
